Repository BChangs99/DSCI_573_Lab4_BDFJ, pull requests merged in 2024-12, with the labels that each got.

#2 Read and split data
  .OTTER_LOG
  lab4.ipynb
Labels: enhancement, bug fix

#6 eda created
  .OTTER_LOG
  data/raw/.AB_NYC_2019.csv.icloud
  data/raw/.UCI_Credit_Card.csv.icloud
  lab4.ipynb
Labels: enhancement

#14 q8 + q9 + q15 writeup
  .OTTER_LOG
  lab4.ipynb
Labels: enhancement

#15 Rough draft of labs (values need to be updated)
  lab4.ipynb
  models/lgbm_random.pickle
  results/optimized_results.csv
Labels: documentation, enhancement
